### ISSUE TITLE
Incomplete description of magic-mode-alist

### ISSUE THREAD

**Issue by seagle0128** [casouri/ivy-filthy-rich#4]
It seems the description is incorrect for some commands. e.g. `magic-mode-alist`, only `Alist of buffer beginnings vs.` is displayed, while the whole description is `Alist of buffer beginnings vs. corresponding major mode functions.`.

**Comment by casouri** [comment]
Ah, the problem is the period in "vs." The function matches "the first sentence" of the description, and that period fooled it. 

Maybe I can change the regex to match period followed by a newline. However, I'm not sure if there is any pitfall in that pattern.

What do you think?

**Comment by seagle0128** [comment]
Yeah, I also think the root cause is the regex for the first sentence.

**Comment by casouri** [comment]
I'll change it. If any other problem arises, we just deal with it.

**Comment by casouri** [comment]
I tested it and it looks fine. Could you also give it a test?

**Comment by seagle0128** [comment]
It doesn't work for me. `ifrich--get-doc-property` and `ifrich--get-face` also need to be changed?

**Comment by casouri** [comment]
Yeah I changed them. It should work now. Sorry.

**Comment by seagle0128** [comment]
What happened?

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(^.+?\\.\\)\n" nil)
  (if (string-match "\\(^.+?\\.\\)\n" doc) (match-string 1 doc) (if (string-match "^.+?\\." doc) (match-string 0 doc) nil))
  ifrich--get-doc-summary(nil)
  (or (ifrich--get-doc-summary doc) "")
  (list (or (ifrich--get-doc-summary doc) ""))
  (let ((doc (documentation-property (intern candidate) 'variable-documentation))) (list (or (ifrich--get-doc-summary doc) "")))
  ifrich--get-doc-property("*undo-tree-id-counter*")
  funcall(ifrich--get-doc-property "*undo-tree-id-counter*")
  (let* ((p (if (and nil (not (eq nil 'eq))) (assoc 'value format-element nil) (assq 'value format-element))) (v (funcall func candidate))) (if p (setcdr p v) (setq format-element (cons (setq p (cons 'value v)) format-element))))
```

**Comment by casouri** [comment]
`doc` -- the documentation of the symbol -- is `nil`. I modified the code so it uses empty string instead.

**Comment by seagle0128** [comment]
Fixed and closed.
