### ISSUE TITLE
ivy broke when searching

### ISSUE THREAD

**Issue by casouri** [casouri/ivy-filthy-rich#5]
Transferred from #3.

Ivy stops updating candidates after you typed some characters.

And an error occurs: 

```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)
```

**Comment by casouri** [comment]
@seagle0128 I'll find a time and try to use your config to reproduce the bug. Although it seems stupid, I hope you can make sure you use the lasted version again. Because when I update to the latest version the bug disappears.

**Comment by seagle0128** [comment]
Confirmed and tested just now. I'm 100% sure using the latest version. Searching with `ivy--regex-plus` and `ivy--regex-ignore-order` are broken, while `ivy--regex-fuzzy` is not.

**Comment by casouri** [comment]
cloning you config 😃 I got to find this creepy bug

**Comment by casouri** [comment]
I tried with your config but didn't hit that bug.

I cloned your config, opened `ivy-filthy-rich.el` and `M-x eval-buffer`, `M-x ivy-filthy-rich-mode`, then `C-h v`: I tried several times and it worked fine.

<img width="659" alt="screen shot 2018-07-02 at 4 36 34 pm" src="https://user-images.githubusercontent.com/13118647/42154472-69d3e796-7e18-11e8-9ff3-9a84be3c2e61.png">

Try this: 
Download https://raw.githubusercontent.com/casouri/ivy-filthy-rich/blob/master/ivy-filthy-rich.el
then open and evaluate it.

If that works, it's the problem with the packaging, if not, there is a hidden bug.

**Comment by seagle0128** [comment]
Weird... I cannot access https://raw.githubusercontent.com/casouri/ivy-filthy-rich/blob/master/ivy-filthy-rich.el, do you mean https://raw.githubusercontent.com/casouri/ivy-filthy-rich/master/ivy-filthy-rich.el? Did you try `C-x b`? It still doesn't work for me. `C-h v` and `C-h f` work.

**Comment by casouri** [comment]
Thanks! I was able to reproduce it. 

The problem is ivy passing in some candidates that are not buffer names, and info functions (`get--dir`, `get--major-mode`) returned nil.

I guess you have a package that adds some recentf history to switch-buffer candidates?

**Comment by seagle0128** [comment]
I am using `recentf-mode`. 

It does work now. Thanks!
