### ISSUE TITLE
[Feature] Show shortcuts of commands?

### ISSUE THREAD

**Issue by seagle0128** [casouri/ivy-filthy-rich#6]
Is it possible to show shortcuts of the commands as the original transformer as well?
The shortcuts are also useful.

And , did you submit to mepla?

**Comment by casouri** [comment]
Yeah, I guess this package is ok now. I'll submit a PR to melpa.

**Comment by seagle0128** [comment]
Thanks for quick fixing. 
But seems that `ifrich-set-function` wasn't called in the minor mode.

**Comment by casouri** [comment]
Right, I need to delete that. It was for debugging purpose. 

Also I added support to add custom transformers.
